# Generated by Django 3.2 on 2021-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=200)),
                ('nom_equipo', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('K_A_D', models.CharField(max_length=200)),
                ('K_R', models.CharField(max_length=200)),
                ('K_D', models.CharField(max_length=200)),
                ('HS', models.CharField(max_length=200)),
                ('mapa', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('elo', models.CharField(max_length=200)),
            ],
        ),
    ]
