# Generated by Django 3.2 on 2021-05-25 13:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('portfolio_type', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='portfolio/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('client', models.CharField(max_length=45)),
                ('website', models.URLField(blank=True, null=True)),
                ('complete_date', models.DateField()),
                ('is_draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_portfolio.category')),
            ],
        ),
    ]
