# Generated by Django 3.2 on 2021-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, default='img/blog_post.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
